README.md

I overlooked that the `ci` in the README path to the shield graphics should be in fact `CI`.

docs: correct uppercase/lowercase typo

---

workflow/Snakefile
workflow/envs/tin-score-calculation.yaml

After upgrade TIN score repo to `0.6.3` we need to update it here too.

chore: bump TIN score version

---

README.md
install/environment.root.yml
install/environment.yml
profiles/local-conda/config.yaml
profiles/slurm-conda/config.yaml

Fixes #18 
Strangely enough the previous problems with `cudadapt` output inconsistencies are no longer there. Maybe they have updated their build at the Anaconda Cloud(?)
Also Fixes #52, which we discovered by the way.
CC @ninsch3000

chore: change conda pkg manager to mamba

---

workflow/Snakefile

rule `sort_genomic_alignment_samtools` created an unnecessary subdirectory within `results/samples`.    
removed tmp dir for samtools sort as per default the tmp files are written alongside the out file [(see samtools sort manual)](http://www.htslib.org/doc/samtools-sort.html#OPTIONS)
Fixes #34

Results dir

---

resources/config_schema.json
workflow/Snakefile
workflow/scripts/zarp_multiqc_config.py

Config params for MultiQC logo (img/url) are optional now: empty string or param absence result in no logo in the final report.
Fixes #72

chore: turn MultiQC logo config params optional

---

workflow/scripts/htsinfer_to_tsv.py

fix: if read len array empty, do not try max

---

workflow/scripts/htsinfer_to_tsv.py

error flag was initialized to "False" inside a function; if that function is never called the variable e_flag is unbound; initializing it at top of script now

fix(htsinfer): initialize error flag in global scope

---

workflow/Snakefile
workflow/rules/paired_end.snakefile.smk
workflow/rules/single_end.snakefile.smk

feat: memory issues, cutadapt speedup

---

workflow/Snakefile

Increased the starting required memory for the sort_bed_4_big rule, as it was running out of memory 
in mouse data.

fix: sort_bed_4_big memory increase as starting point

---

.github/workflows/ci.yml
.gitignore
config/config.yaml
install/environment.dev.yml
tests/test_format/test_snakefmt.sh
tests/test_format/test_snakemake_lint.sh
tests/test_htsinfer_workflow/test.local.sh
workflow/Snakefile
workflow/rules/common.smk
workflow/rules/htsinfer.smk
workflow/rules/paired_end.snakefile.smk
workflow/rules/single_end.snakefile.smk
workflow/rules/sra_download.smk

For the workflow to be compatible with snakemake workflows catalogue, there are specific guidelines for formating (using snakefmt) and linting (snakemake --lint)
Fixes #12 

feat: addition of snakemake compatible format and linting

---

.github/workflows/ci.yml
workflow/Snakefile

Fix issue with snakefmt (remove consecutive comment lines) and remove exact mamba version from CI.
Fixes #109 #110 

fix: issue with snakefmt, issue with mamba version in CI

---

.github/labeler.yml
.github/release.yml
.github/workflows/labeler.yml
.github/workflows/main.yml

- New labels have been manually added in the repo, called enhancement and breaking-change. 
- A new github action labeller attaches appropriate label according to PR-title
- The .github/release.yml has been modified to accept the approved label names to assign PRs to appropriate categories
Fixes #127
Changes to workflow inputs (sample table and/or configs)
* major (add **BREAKING CHANGE:** in the beginning of the PR title)
* more fields/properties are required 
* existing ones are dropped entirely 
* minor (add **feat:** in the beginning of the PR title)
* optional fields/properties are added
* required ones are made optional
Changes to workflow outputs
* major (add **BREAKING CHANGE:** in the …

fix: release notes categories

---

workflow/rules/htsinfer.smk

Don't keep default `nan` when reading samples table in `htsinfer.smk`, otherwise `nan` will be used instead of empty string in call to htsinfer.
Fixes #135 
Changes to workflow inputs (sample table and/or configs)
* major (add **BREAKING CHANGE:** in the beginning of the PR title)
* more fields/properties are required 
* existing ones are dropped entirely 
* minor (add **feat:** in the beginning of the PR title)
* optional fields/properties are added
* required ones are made optional
Changes to workflow outputs
* major (add **BREAKING CHANGE:** in the beginning of the PR title)
* changes lead to removal/change of existing outputs (format or location)
* minor (add **feat:** in the beginning of the …

fix: do not use nan in htsinfer call

---

workflow/rules/htsinfer.smk
workflow/scripts/htsinfer_to_tsv.py

allow global error flag variable to be changed inside function. Added `global` keyword before variable inside the function definition, in order to allow the function to assign something to that variable. Additionally, changed test for nan to numpyesque call.
Fixes #136 

fix: allow global error flag variable to be changed inside function

---

workflow/rules/htsinfer.smk

Updated `htsinfer.smk` to pin the docker image for HTSinfer with the tag `latest` instead of `0.9.0`.

perf: pin htsinfer docker image to latest

---

tests/test_htsinfer_workflow/test.local.sh
workflow/rules/htsinfer.smk

reading log and cluster log directory paths from config, instead of building them inside the Snakefile. Like this, compatibility with other parts of ZARP-cli is ensured.
Fixes #145 

feat(htsinfer): interface log and cluster log dirs via config.yaml

---

install/environment.dev.yml
tests/test_htsinfer_workflow/expected_output.md5
workflow/Snakefile
workflow/envs/cutadapt.yaml
workflow/rules/paired_end.snakefile.smk
workflow/rules/single_end.snakefile.smk

Upgrading Cutadapt resolves the issue (only tested for Conda execution).
Fixes #152 

fix: Cutadapt compression level problem

---

workflow/Snakefile

- Increase default memory allocation for rule `sort_bed_4_big` from 2048 to 4096 Mb
Fixes #160 

fix: too little RAM allocated for BED sorting

---

workflow/rules/common.smk

- Address deprecation warning issued by Pandas for treating keys as positions when using `Series.__getitem__` in function `get_sample()` defined in `workflow/rules/common.smk`
Fixes #158 

chore: deprecation warnings for get_sample()

---

README.md
install/environment.cli.yml

- Update ZARP-cli installation instructions
- Recommend ZARP-cli for most use cases

docs: update ZARP-cli installation instructions
